### ISSUE TITLE
Structure Proposal

### ISSUE THREAD

**Issue by crymis** [KordonDev/marriage#27]
* Start: Bild von Lisa & Arne + Wilkommenstext + Link zum Rückmelden [WAS ]
* Location: Ort und Beschreibung (Platz für x Personen), Anreise [WO]
* Ablauf: Agenda/ Timetable (statisches HTML) [WANN]
* Rückmeldung: Personen + Essen [WER]
* Wunschliste, Kuchenliste [WIE]
* Admin-View
* Countdown: Wie lange noch?
* Gäste-Counter: Wie viele haben zugesagt?
* Impressum

**Comment by KordonDev** [comment]
# Start
* Bild
* Willkommen
* Link zur Rückmeldung
# Feier
* Programm
* Location
* ? Google Maps Navigation
# Rückmeldung
# Kuchenliste
# Geschenkliste
