### ISSUE TITLE
Redesign CakeList

### ISSUE THREAD

**Issue by KordonDev** [KordonDev/marriage#29]
/cakeList needs a redesign

- [x] ghost button
- [x] Abstand nach oben
- [x] Sichtschutz zu Inputs
- [x] Form um Inputs
- [x] Nur eigene Daten Löschen
- [x] Loadingspinner
- [ ] Mehrere Kuchen (Sektempfang / Nachtisch)

**Comment by Safi1012** [comment]
![desktop hd](https://user-images.githubusercontent.com/3514796/47944251-aff41780-defa-11e8-86ab-f200b76102c6.png)
![mobile](https://user-images.githubusercontent.com/3514796/47944252-b08cae00-defa-11e8-92bb-88daca0497ab.png)
