### ISSUE TITLE
/Feier Design

### ISSUE THREAD

**Issue by KordonDev** [KordonDev/marriage#33]

**Comment by crymis** [comment]
![party_view_scrolled](https://user-images.githubusercontent.com/3726683/47944256-ba161600-defa-11e8-8d9f-bd6a23354fc5.png)
![party_view](https://user-images.githubusercontent.com/3726683/47944257-ba161600-defa-11e8-8f51-d8dd83603084.png)

**Comment by KordonDev** [comment]
closed by #52
